CUDA_VISIBLE_DEVICES=0 python supervised_finetuning.py \
    --model_name_or_path /root/MedicalGPT/models/Qwen2.5-1.5B-Instruct \
    --train_file_dir ./data/finetune_mix/medical_dominant_85_15/train \
    --validation_file_dir ./data/finetune_mix/medical_dominant_85_15/val \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --do_train \
    --do_eval \
    --template_name qwen \
    --use_peft True \
    --qlora True \
    --load_in_4bit True \
    --model_max_length 2048 \
    --max_train_samples -1 \
    --max_eval_samples 200 \
    --num_train_epochs 1 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.03 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 500 \
    --eval_strategy steps \
    --save_steps 1000 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 16 \
    --preprocessing_num_workers 4 \
    --output_dir outputs-sft-medical-85-15-qwen2.5-1.5b-3090-v1 \
    --overwrite_output_dir \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 16 \
    --lora_alpha 32 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --fp16 \
    --device_map auto \
    --report_to tensorboard \
    --gradient_checkpointing True \
    --ddp_find_unused_parameters False \
    --cache_dir ./cache
